main:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "About"
    url: "/about"
    weight: 2
  
  - name: "Docs"
    url: "/docs"
    weight: 3


buttons:
  - name: "Email us"
    url: "mailto:ctfer-io@protonmail.com"
    weight: 4

footer:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "About"
    url: "/about"
    weight: 2  
  
  - name: "Docs"
    url: "/docs"
    weight: 3
